---
title: "Developing an interdisciplinary research program"
fontsize: 12
output: pdf_document
---

I have made a career of helping others become successful researchers. In particular, I love working with inexperienced researchers, taking them from an insecure and uncertain beginning to an increasing level of confidence and sophistication. This bottom up approach to developing a research infrastructure has a nice side benefit. Becuase the inexperienced researchers come from a broader and more diverse demographic pool than seasoned researchers, helping them succeed helps produce a more diverse work force.

Make no mistake, though. I can work just as well with seasoned researchers. To cite just one example, my partnership with a nationally recognized expert in reproductive toxicology at the National Institute for Occupational Safety and Health led to almost a dozen peer-reviewed publications, two of which won major awards.

My contributions to the Smart Living initiative would focus on three areas: utilizing existing data resources, improving the research process, and addressing outcome disparities.

## Utilizing existing data resources

There are many large databases available at no cost which can greatly improve the research process. I summarized some of the most important of these in an article, U.S. Census Bureau, for the Encyclopedia of Big Data (in press). These data sets are valuable in their own right but are also important for establishing an appropriate denominator for any study utilizing geographic data.

Many large databases require specialized knowledge of database storage modalities. Because of the massive number of possible diagnoses, procedures, and medications that are documented in the electronic health record, for example, it requires storage in a relational database using an Entity-Attribute-Value model. My interest in developing a short course on SQL, in fact, was inspired by my work on the electronic health record.

## Improving the research process

In my book, Statistical Evidence in Medical Trials, I highlight an interesting summary of research in schizophrenia conducted by Ben Thornley and Clive Adams in 1998. They reviewed 2,000 of schizophrenia conducted between 1947 and 1997. The findings were very bleak. Far too often, researchers studied the wrong patients, they did not study enough of them, and they did not study them long enough.

Throughout my career, I have been on a mission to improve the research process. Many sample size shortfalls, for example, come from poor estimates of the accrual rate for research subjects. I have several publications in top quality journals on Bayesian models for accrual. I co-authored an invited editorial about the process of identifying a scientifically relevant difference so that a study could examine practical as well as statistical significance. Most recently, I have been promoting the reproducible research movement both in a local Statistics journal club and in a webinar for a national consulting group.

## Addressing outcome disparities

I have worked closely with several researchers on outcome disparities, most notably in the African American community. There is a lot that statistics can say about disparities due to race, gender, and income. The process of subgroup analysis, often scorned in the research community, is a vital approach for identifying how best to improve health in the future. If subgroups are identified (with appropriate statistical safeguards against multiple comparisons) that tells you that new health care interventions can be economically targeted to specific demographic subgroups. If your subgroup analysis comes up empty, that tells you that new health care interventions should be applied to all groups equally. Either way, you win.