---
title: "Teaching interests and experience"
fontsize: 12
output: pdf_document
---

I have taught in a wide range of non-traditional formats: short courses at regional, national, and international conferences, and webinars for a geographically diverse audience. I take great pride in my repeated invitations to give talks to the same organizations. 

I want to highlight one talk, Guidelines for Good Graphics, that illustrates my work in data visualization. I will then summarize two short courses, Writing a CAM grant, and Statistics for Medical Librarians, which show how I used small group exercises to enhance the learning experience. I also want to mention a series of classes I have developed at UMKC that show my ability to develop on-line courses.

## Guidelines for Good Graphics

Back in the 1990s, before the term "data visualization" came into popularity, I developed a one hour presentation, "Guidelines for Good Graphics," that was so well received that I was invited to present it for almost a dozen different research groups. It drew on our knowlege of the human perception process and reviewed the pioneering work of Bill Cleveland and Edward Tufte. A lot has changed since the 1990s, but I have kept current with the recent efforts by Hadley Wickham and Leland Wilkinson that have led to the ggplot2 library in the R programming language.

## Writing a CAM Grant

I was fortunate to partner with prominent statisticians with the National Institutes for Health and Palmer College of Chiropractic to give a short course, Writing a CAM grant, at the International Research Conference on Complementary Medicine in 2012 and 2014. My talks covered selecting an appropriate sample size, pilot studies, and characteristics of a good statistical consultant. We developed small group exercises where each group was given a different research paper and asked to propose a research design that would extend the results of the that paper and form the basis of a new research grant. The small group exercises led to a spirited discussion about competing research designs.

## Statistics for Medical Librarians

I also had a profitable partnership with a medical librarian and produced a very popular class, Statistics for Medical Librarians, that was taught in an online format and at several regional and national meetings of the Medical Library Association. One highlight of these classes was the use of small group exercises where we showed each group a different research abstract and asked them to interpret the confidence intervals or p-values that appeared in the abstract. Our students really appreciated seeing and having to make sense of statistics as they appear in the wild.

## Introduction to R, SAS, and SPSS

I have helped develop many of the classes needed for a new Masters degree program in Bioinformatics. More recently, I worked on a team to develop a series of one credit hour classes: Introduction to R, Introduction to SAS, and Introduction to SPSS. This was in response to an external advisory panel suggestion that our student would benefit from more experience with programming. These classes cover the basics of data input, data manipulation, simple graphics, and simple statistics. In addition to addressing the concerns of the advisory panel, these classes allow other classes in our program to save lecture time on these packages and refocus them on additional statistical topics. These classes were originally taught as a live lecture in the computer laboratory but to meet student demands, we converted them into an asyhchronous online format. I am currently working with an expert database administrator to develop a fourth class, Introduction to SQL.