---
title: "Professional resume of Stephen D. Simon"
fontsize: 12pt
output: pdf_document
---

## Contact information

* 14814 Granada Ct, Leawood, KS 66224
* 913-814-9942
* mail@pmean.com

## Personal

* Born June 22, 1956. Married with one child.

## Education

* Ph.D., University of Iowa, Statistics, December 1982
* M.S., University of Iowa, Statistics, December 1978
* B.A., University of Iowa, Mathematical Sciences, July 1977

## Experience

* Full Professor, part-time, Department of Biomedical and Health Informatics, University of Missouri-Kansas City (UMKC), February 2009 to present. In this position, I started the Research and Statistical Consult Service. With a second consultant, we helped with the planning of research studies, analyzed the data coming from these studies, and co-authored research presentations and publications. We helped researchers obtain internal and external grant funding. I left work with the Research and Statistical Consult Service in January 2016 because of the demands of a major research grant, but the service is still being run by another faculty member. In addition to this work, I helped with the introduction of a new Master's degree in Bioinformatics and a graduate certificate in clinical research. I helped develop three new courses (Introduction to R, Introduction to SAS, and Introduction to SPSS) including the preparation of materials for an online version of the class. When Spring semester 2018 arrives, I will have taught all three of these classes. I have provided guest lectures for other classes (Responsible Conduct of Research, Clinical Research Methodology).

* Independent Statistical Consultant, P.Mean Consulting, July 2008 to present. In this position, I have provided consulting on research design and data analysis to clients. I have specialized in helping doctoral students who are struggling with the requirements of their dissertation. I also have provided webinar classes for Novartis and The Analysis Factor. When I first started my consulting business, I could not find much information about the practical aspects of statistical consulting (e.g., contracts, insurance, and billing), so I developed resources on my website and blog and gave presentations and short courses on setting up a consulting practice.

* Research Biostatistician, Office of Medical Research, The Children's Mercy Hospital and Clinics (CMH), May 1996 to October 2008, with a joint appointment as Associate Professor (promoted to Full Professor, September 2007) in the School of Medicine at the University of Missouri-Kansas City. In this position, I provided statistical consulting to the doctors, nurses, and other health care professionals at CMH. Before I arrived, there was no statistical support for researchers, so I had to develop a consulting system from scratch. This included a series of training classes that helped researchers to become self-sufficient for some of their less complex data analyses. I wrote some informational handouts for clients and placed these on the web. It started slowly, but averaging one or two handouts per week, I ended up with a website in 2008 that had over 1300 pages. This website is regularly cited in both paper and electronic resources for research methodology and pops up high on the list of search engines when technical terms in research are entered. I helped many researchers get funding (both internal and external) through research grants. I worked closely with the Institutional Review Board to ensure that protocols submitted to them addressed concerns about scientific merit and protection of confidentiality. I also provided training in the ethical conduct of research. I also worked closely with the effort to implement Evidence Based Health Care at CMH and participated in numerous journal clubs. In 2006, I published a book on the statistical issues associated with critical appraisal of research evidence. I was the sole statistician at CMH from 1996 to 2007 and oversaw a massive expansion in the quantity and quality of research conducted there.

* Chief, Statistics Activity, Division of Biomedical and Behavioral Science, National Institute for Occupational Safety and Health, December 1987 to May 1996. I supervised a staff of two research statisticians and two computer specialists. I oversaw the administration of a Local Area Network for more than 100 users, and the maintenance of administrative and research data on a client-server database. I reviewed and approved all project protocols in the Division prior to the start of any experimental work. I also worked directly with project officers in designing experiments, analyzing data, and writing results for publication. I was also very active in the NIOSH effort to adopt Total Quality Management (TQM), serving as team leader, facilitator, or member of a variety of quality teams. I also provided many informal training seminars in TQM for NIOSH employees. 

* Research Statistician, Division of Biomedical and Behavioral Science, National Institute for Occupational Safety and Health, July 1987 to November 1987. The woman who hired me for this position left shortly after I arrived and I was quickly promoted to her position.

* Assistant Professor, Department of Applied Statistics and Operations Research, Bowling Green State University, September 1981 to May 1987. Duties included teaching and research. I taught Business Statistics, Experimental Design, Linear Models, Multivariate Statistics, Nonparametric Statistics, Regression, and Statistical Packages. I published articles and made presentations in the areas of numerical accuracy, robust statistics, and computer applications. During the Summer of 1986, I also served as the Assistant Director of the Statistical Consulting Center. 

* Adjunct Instructor, Department of Statistics, University of Iowa, June to August 1981. I taught a three credit hour class, Statistical Computing.

* Research Assistant, Statistical Consulting Center, University of Iowa, June 1979 to August 1981. I was the student director of the Statistical Consulting Center. Under the direction of a faculty adviser, I met with faculty and graduate students and provided guidance and support for the design of research studies and the analysis of the data from those studies.

## Current grant funding

* Frontiers: University of Kansas Clinical and Translational Science Institute (NIH UL1 TR002366, Principal Investigator: Richard Barohn). The Heartland Institute for Clinical and Translational Research has been a catalyst for bringing together translational science investigators and stakeholders across the KC region, and beyond. The vision of Frontiers is to contribute to and lead national efforts to transform the way we do clinical and translational research (CTR), and to ensure research is more rapidly and more efficiently translated to the point of care so that it may contribute to improved health. I am funded at 10% effort starting in September 2017.

## Completed research grants

* Greater Plains Collaborative (PCORI HSRP20162063, Principal Investigator: Russ Waitman). The Greater Plains Collaborative (GPC) is a new network of 10 leading medical centers in 7 states committed to a shared vision of improving healthcare delivery through ongoing learning, adoption of evidence-based practices, and active research dissemination. Role: Consultant. I was funded at 25% effort from February 2016 to August 2017 when my efforts were switched to the Frontiers grant described above.

* Increasing HIV Screening in African American Churches. (NIH R01 MH099981, Principal Investigator: Janette Berkley-Patton). The primary aim of the proposed study is to conduct a clustered, randomized community trial to fully test our culturally/religiously-tailored church-based HIV screening intervention against a standard information intervention on HIV screening rates at 6 and 12 months with adult AA church members and community members who use church outreach services. Role: Co-investigator. I was funded at 5% effort from July 2013 through January 2016, but had to discontinue work on this grant because of other work commitments.

* Role of cytochrome P450 in alcohol-mediated effects on antiretrovirals and HIV-1. (NIH R01 K2304028, Principal Investigator: Santosh Kumar). Our central hypothesis is that in monocytes/macrophages alcohol-mediated oxidative stress causes enhanced HIV-1 replication via pathways mediated through CYP2E1, and alcohol-mediated decrease in the efficacy of PIs and increase in PIs-mediated toxicity concurrent with increase in the rates of HIV-1 replication is directly mediated through CYP3A4. Role: Co-investigator. I was funded at 8% effort in the first year with increasing support in future years, but support was lost in July 2014 when the PI moved to a different institution.

* HIV Testing in African American Churches. (NIH K01 MH082640, Principal Investigator: Janette Berkley-Patton). This Mentored Research Career Award provides support for Dr. Jannette Berkley-Patton to obtain the requisite training and expertise to develop and test a church-based intervention to increase HIV testing among African Americans. Role: Co-investigator. I was funded at 5% effort from April 2012 through July 2013.

* Bayesian prediction for interim review of studies with slow patient accrual. (Intramural grant, Kansas University Cancer Center). Patient recruitment for medical research is a huge challenge, especially for cancer trials. Slow patient accrual leads to delays in the completion of the study, sample size shortfalls, or both. This can disrupt the risk/benefit ratio of a study, and raise serious ethical problems for Institutional Review Boards (IRBs) and Data Safety and Monitoring Boards (DSMBs). We wish to fundamentally change the way clinical trials are planned and monitored by providing a rigorous framework for accrual based on Bayesian principles. Accrual estimates depend largely on how much experience clinicians have had in running previous trials, and how similar the current trial is to those previous trials. The Bayesian method of eliciting prior distributions offers a major innovation to accrual because it provides a proven method for quantifying subjective experiences and opinions about accrual. Bayesian methods offer an additional innovation because they allow the combination of these subjective experiences and opinions with actual accrual data during the conduct of the trial to produce a continuously updated probability that a trial will finish within the proposed time frame with the required number of patients. (This grant was awarded in May 2013, but funds supporting salary costs for Dr. Simon were removed prior to approval.)

* Ensuring Medication Safety in Pediatric Emergencies. (FDA U01 FD004249, Principal Investigator, Susan Rahman). In no other patient population is there more calculation and manipulation of drug doses than in children. The need to individualize pediatric doses introduces the potential for errors along the entire process of drug delivery from prescribing and transcribing the dose to diluting, compounding, dispensing and administering the final formulation. Consequently, dosing errors represent the most common type of medication error in children. Error rates in children are 3x more common than the corresponding rates in adults and in hospital settings the rate of medication errors on pediatric wards is second only to those in intensive care units. Despite the abundance of weight estimation strategies, there remains a critical need for methods that are accurate across a wide range of pediatric ages, weights, lengths, nationalities and body compositions. Consequently, we undertook the development and validation of a weight estimation method that incorporates surrogates for both stature and body habitus, requires no subjective assessment and performs robustly independently of age and length over a broad range of weights. Role: Consultant (September 2011 through September 2012).

* Health Educators in the Emergency Department to Improve Sexual Health Care for Adolescents. (NIH KL2 RR033177 & UL1 RR033179, Principal Investigator: Melissa Miller). Our objective in this application is to develop an ED-based intervention for adolescents aged 14-19 years that will increase access to care, provide more timely detection of STIs and pregnancy, and ultimately reduce adolescents' risk for STIs and unintended pregnancies. Role: Consultant. I was funded at an hourly rate rather than percentage effort from August 2011 through July 2012.

* CAM, Medical Service Utilization, and Quality of Care among Patients with Musculoskeletal Conditions (NIH R01 AT000891, Principal Investigator: Bill Lafferty). To inform health policy decision making at the individual and societal level by assessing the effect of complementary and alternative medicine (CAM) provider use on three primary outcomes: costs, service utilization, and quality of care for the treatment of musculoskeletal conditions. I was funded at 25% effort from November 2010 to August 2011.

* NDNQI Services Agreement Work Order No. 3 (Principal Investigator: Nancy Dunton). Funded by the American Nurses Association. The major goals of this project are to develop a method for unit-based acuity adjustment and to develop a method to calculate hospital level indicators. I was funded at 25% effort from February through April 2008.

* Pediatric Pharmacology Research Unit (NIH U01 HD31313. Principal Investigator: Greg Kearns). Total direct costs of $361,932 in 2002. The major goal of this project is to conduct basic and translational research focusing on regulatory events in pharmacogenetics, the ontogeny of important drug metabolizing enzymes, and pharmacodynamics that will advance our understanding of age-related differences in drug disposition and action. I was funded at 3% effort from May 1996 to December 2003.

* Sex, SLE, and Signal Transduction (NIH R01 AR50878. Principal Investigator: Jill Jacobson). Total direct costs of $250,000 in 2002. The major goal of this project is to demonstrate that the increase in immune responsiveness to gonadotropin-releasing hormone in female mice plays a pivotal role in increased incidence of autoimmune disease. I was funded at 5% effort from December 2011 through November 2006.

## Patents

* Co-inventor on U.S. Patent, A System and Method for Monitoring and Analyzing Data Trends of Interest Within an Organization, filed December 2000, and sold to Cerner Corporation, February 2008.

## Awards

* Honorable mention in the R programming contest sponsored by Revolution Analytics, for R functions to predict the completion date for a prospective clinical trial, May 2014.

* Co-author of a research presentation (Nopper A, Wright T, Tee R, Horii K, Simon S, Popovic J, Alon U. Bone Density in Children With Hemangiomas Treated With Systemic Glucocorticoids) which received the ISSVA "R Schobinger Award" for best clinical paper presented during the 16th International Workshop on Vascular Anomalies, June 2006, Milano, Italy.

* Co-author of a research paper (Miller-Hansen DR, Nelson PB, Widen JE, Simon SD. Am J Audiology 2003;24(1);16-18) which received the Editor's Award for the American Journal of Audiology for the most outstanding publication in the calendar year 2003.

* Selected as the winner of the Bluejacket Toastmasters international speech contest for my speech "I married a dog nut," March 2003.

* Selected as the winner of the Bluejacket Toastmasters humorous speech contest for my speech "The one thing that can gross out a doctor," September 2001. This speech also won at the Area K-1 contest, and the Division K contest.

* Co-author of a research paper (Moorman WJ, Skaggs SR, Clark JC, Turner TW, Sharpnack DD, Murrell JA, Simon SD, Chapin RE, Schrader SM [1998]. Male reproductive effects of lead, including species extrapolation for the rabbit model. Reproductive Toxicology 12(3): 333-46.) which was the winner of the Alice Hamilton Award for 1999 for the best research paper in occupational safety and health (Biological Sciences Category).

* My presentation "Medical Statistics Case Studies on the Web" was voted as the best presentation in the area of Teaching Statistics in the Health Sciences at the Joint Statistical Meetings in Anaheim CA, August 1997.

* Selected as the winner of the Cincinnati NIOSH Toastmasters humorous speech contest for my speech "Puns and Poetry," September 1994, and as winner of the Cincinnati NIOSH Toastmasters Table Topics (extemporaneous speech), also September 1994 for my response to the question "What famous person would you like to have lunch with?" I went on to represent the Cincinnati NIOSH Toastmasters at the October 1994 Area 32 humorous speech contest, where (using the same humorous speech) I again won the competition.

* Received Public Health Service Commendation Medal in July 1994 for my oversight of a laboratory modernization effort that included the use of a client-server data base system, remote monitoring of laboratory systems, automation of chemical workups using laboratory robotics, laptop systems for data collection in the field, and real-time data collection interfaces for Liquid and Gas Chromatography instruments.

* Co-author of a research paper (Stettler LE, Platek SF, Riley RD, Mastin JP, Simon SD [1991]. Lung particulate burdens of subjects from Cincinnati, Ohio urban area. Scanning Microscopy 5(1):85-94) which was a finalist for the Alice Hamilton Award for 1992 for the best research paper in occupational safety and health.

* Co-author of a research paper (Schrader SM, Turner TW, Simon SD [1990]. Longitudinal Study of Semen Quality of Unexposed Workers: II. Sources of Variation of Sperm Head Morphometry. Journal of Andrology 11(1):32-39) which was the winner of the Alice Hamilton Award for 1991 for the best research paper in occupational safety and health. This paper was also nominated by NIOSH for the Charles C. Shepard Science Award for best scientific research paper in CDC.

* Received Public Health Service Achievement Medal in April 1990 for producing cost savings and greater operational efficiency through the use of micro-computer analysis of statistical data.

* Co-author of a research paper (Schrader SM, Turner TW, Breitenstein MJ, Simon SD [1988]. Longitudinal Study of Semen Quality of Unexposed Workers. I. Study Overview. Reproductive Toxicology 2:183-190) which was the winner of the Alice Hamilton Award for 1990 for the best research paper in occupational safety and health.

## Professional organizations and special committee assignments

* President of the Kansas City R Users Group (December 2014 to present). This group meets monthly to share information and experiences with the R programming language and statistical analysis package. When I took over, the group was threatening to fold because meetings had as few as three or four people attending. I converted the group's publicity from a proprietary email notification system to meetup.com, changed the format of the meetings to alternate between beginner and advanced sessions, found an alternate meeting site with better seating and audiovisual equipment, and recruited new speakers for the meetings. The group has increased its membership and now has 10 to 20 attendees at most meetings.

* Member of the Complementary and Alternative Medicine (CAM) Statisticians committee within the American Statistical Association (ASA) (August 2012 to present). This group meets annually at the Joint Statistical Meetings and conducts additional business by email and telephone. The members share experiences and concerns about statistical issues associated with CAM research studies, learns about research developments at the National Center for Complementary and Integrative Health, and provides outreach to CAM practitioners who wish to study their therapies in a rigorous and controlled fashion.

* Member of the ASA Traveling Course committee (August 2004 to August 2006). The Traveling Course committee solicits speakers who are willing to offer a one day short course on an important topic in Statistics. This course is available for three local ASA chapters. The committee reviews applications to host the course and selects three chapters to host the course. The committee then arranges all of the travel and other logistics along with the appropriate local ASA chapter officers.

* Member of the Kansas University Medical Center Data Safety and Monitoring Executive Committee (January 2002 to June 2008) and Vice-Chair (January 2005 to June 2008). The Data Safety and Monitoring Board provides on-going review of research projects at the Kansas University Medical Center where there is a conflict of interest for the primary investigator or where early stopping of a trial would be considered for early evidence of efficacy or early evidence of an unacceptable rate of adverse events.

* Member of the University of Missouri Kansas City School of Medicine search committee for a M.S. Biostatistics position (April 2007 to June 2007). Assisted with review of resumes, personal interviews, and evaluation.

* Member of the University of Missouri Kansas City School of Medicine search committee for a Ph.D. Biostatistics position (July 2006 to April 2007). Assisted with review of resumes, personal interviews, and evaluation.

* Member of the University of Missouri Kansas City School of Nursing search committee for a Ph.D. Biostatistics position (September 2005 to November 2005). Assisted with personal interviews and evaluation.

* Vice President Education (July 2001 to June 2003), President (July 2000 to June 2001) and Sergeant-at-Arms (February 2000 to June 2000) for the Bluejacket Toastmasters Club. Toastmasters provides a mutually supportive and positive learning environment for the development of communication and leadership skills. As Vice President Education, I prepared a program of speakers and evaluators for each meeting and reviewed credentials of members applying for Competent Toastmaster, Able Toastmaster, and Distinguished Toastmaster certifications. As president, I provided support and guidance to all the other officers of the club and represent the club to the parent organization (Toastmasters International) and to outside groups. As Sergeant-at-Arms, I prepared the room for each meeting and provided refreshments.

* Council of Chapters Representative (July 2001 to June 2004), President (July 1998 to June 2000), and Vice President (July 1997 to June 1998) for the Kansas/Western Missouri chapter of the ASA. The Kansas-Western Missouri chapter provides statistics seminars and other presentations from local and national experts for locations in Western Missouri and in Kansas. As Council of Chapters representative, I served as a liaison between the local ASA chapter and the national office. As president, I provided support and guidance to all the other officers of the chapter and represented the club to the parent organization (the American Statistical Association). As vice-president, I recruited speakers and organized the time and location of statistics presentations.

* Founder and president of the steering committee for the Childrens Mercy Hospital Internet Users Group, April 1997 to June 1998. The Internet Users Group provides a forum for individuals to share their expertise on Internet topics. The steering committee identifies speakers and topics for meetings and prepares publicity. As founder, I scheduled and ran an organizational meeting for the group, developed the structure and goals of this group, and recruited volunteers for the steering committee. As a president of the steering committee, I arrange meetings of this group and provide overall guidance.

* Member of the DBBS Quality Council, July 1995 to May 1996. The DBBS Quality Council identifies quality problems within DBBS, recruits teams to address these problems, and provides continual oversight and feedback to these teams.

* Secretary/Treasurer of Cincinnati Chapter of the American Statistical Association, July 1995 to June 1996. The Cincinnati chapter provides statistics seminars and other presentations from local and national experts for locations in and around Cincinnati, including Oxford, Ohio. As Secretary/Treasurer, I obtained meeting rooms and appropriate audiovisual equipment for Statistics presentations, prepared publicity for each meeting, maintained the organization's mailing list, and balanced the organization's checking account.

* Member of the Quality Management Advisory Board for the College of Mount St. Joseph, May 1995 to May 1996. The Quality Management Advisory Board provides advice to the College of Mount St. Joseph regarding its newly developed undergraduate degree program in Quality Management. The board consists of representatives of the Cincinnati business and government communities as well as students and faculty from the Quality Management program itself.

* Co-chair of the Statistics, Data Analysis and Modeling Section of the 1995 Midwest SAS Users Group conference in Cleveland OH (with DK Wild). The co-chair provides review of all papers submitted to this section of the conference. I also contacted presenters to verify audiovisual needs and met with presenters prior to the start of the meeting to answer questions. In addition, I performed any necessary troubleshooting before or during the start of each session at the conference, and ensured that evaluation forms were completed and delivered to the conference organizer at the end of each session.

* Cincinnati NIOSH Representative to the Cincinnati Federal Executive Board Reinvention Subcommittee, October 1994 to September 1995. The reinvention subcommittee provides Cincinnati Federal Government agencies with a professional source of expertise on the issues addressed in the National Performance Review, and presents various seminars that address handling change and coping with streamlining initiatives.

* President (July 1994 to June 1995) and charter member (March 1993 to May 1996) of Cincinnati NIOSH Toastmasters. Toastmasters provides a mutually supportive and positive learning environment for the development of communication and leadership skills. As president, I provided support and guidance to all the other officers of the club and represented the club to the parent organization (Toastmasters International) and to outside groups. In April 1995, I earned the Competent Toastmasters Certificate for successful completion of the ten speech projects in the Toastmasters Communication and Leadership Program.

* Team Leader for NIOSH Organizational Climate Survey Team (July 1993 to January 1994), and team member (January 1994 to May 1996). This Organizational Climate Survey Team distributed and analyzed a survey in August and September 1993 to assess the perceptions of NIOSH employees towards Total Quality Management. Our team presented a report detailing our analysis of this survey to the NIOSH Quality Council in December 1993. The team has proposed a revision of this survey, which we plan to implement on a semi-regular basis (e.g., every two to three years) to assess the changes in employee perceptions over time.

* Team Facilitator for DBBS Manuscript Review Team, June 1993 to May 1996. The DBBS Manuscript Review Team applied Total Quality Management principles to implement improvements to the manuscript review procedure that will decrease the time required for internal review while still maintaining quality of the manuscripts. As facilitator, I did not participate in the actual decisions being made, but instead worked to ensure that decisions made are founded on team consensus and full, open, and honest participation from all team members. I also encourage the use of TQM tools such as flow charts and cause-and-effect diagrams.

* Member of NIOSH Surveillance Coordinating Group, January 1993 to May 1996. The Surveillance Coordinating Group coordinates all surveillance related research throughout NIOSH, prepares reports on surveillance activities for the public, and sets standards on variable naming definitions.

* Member of CDC Statistical Advisory Group, October 1992 to May 1996. The Statistical Advisory Group advises the Assistant Director for Science of the Centers for Disease Control and Prevention on matters of policy relating to Statistics.

* Chair of the DBBS Seminar Series committee, September 1992 to August 1994. The Seminar Series committee organizes weekly research and safety seminars for the staff of DBBS, and prepares publicity for these seminars.

* Founder and Co-chair of NIOSH Statistical Discussion Group, July 1989 to May 1996. The Statistics Discussion Group provides a forum for informal discussion of professional issues relevant to Statisticians in the five Cincinnati Divisions of NIOSH and the two Morgantown Divisions. As founder of the Statistical Discussion Group, I scheduled and ran an organizational meeting for the group, developed the structure and goals of this group, and recruited a co-chair for the group. As Co-chair, I was responsible for organizing meetings and for publicity for Statisticians in two Divisions at the Taft Laboratories in Cincinnati.

* Organizer and chair of the executive board for the DBBS Microcomputer Users Group, September 1988 to March 1989, and member of the executive board, April 1989 to June 1990. The DBBS Microcomputer Users Group coordinated microcomputer purchases and provided educational services to the staff of the Division of Biomedical and Behavioral Science. As founder of the Internet Users Group, I scheduled and ran an organizational meeting for the group, developed the structure and goals of this group, and recruited volunteers for the steering committee. I was responsible for coordinating publicity and monthly meetings for this group. I also served as the liaison to the Hamilton Users Group, a similar group for two other divisions in NIOSH.

* Charter President of the Bowling Green IBM PC Users Group, September 1985 to May 1987. I was responsible for recruiting speakers for their bi-monthly meetings, for publicizing these meetings, and for maintaining their membership list. I also supervised the public domain librarian and the SYSOPs of the group's Bulletin Board System.

* President (June 1985 to May 1986); Vice President (June 1984 to May 1985); and Secretary/Treasurer (June 1983 to May 1984) of the Northwest Ohio chapter of the American Statistical Association. The Northwest Ohio chapter provides statistics seminars and other presentations from local and national experts for locations in Northwest Ohio. As president, I provided support and guidance to all the other officers of the club and represented the club to the parent organization (the American Statistical Association). As vice-president, I recruited speakers and organized the time and location of statistics presentations. As secretary/treasurer, I obtained meeting rooms and appropriate equipment for statistical presentations, prepared publicity for each meeting, maintained the organization's mailing list, and balanced the checking account.

## Other professional activities

* Refereed research papers for American Journal of Obstetrics and Gynecology in 2011, BMJ in 2006 and 2007, the Annals of Allergy, Asthma & Immunology in 2003 and 2004, BMC Medical Research Methodology in 2002, the Journal of Andrology, in 1999 and 2000, for the American Statistician, in 1985 and 1992, and for the International Journal of Science and Engineering, in 1983.

* Served on an advisory committee to develop a Health Outcomes Research Masters Degree program for the University of Missouri, Kansas City, October 1999 to February 2000.

* Served as a co-instructor for NIOSH Training Course 553, "Statistical Analysis for Industrial Hygiene Sampling and Decision Making" which was offered on an annual basis from 1988 through 1993. I delivered approximately 6 to 8 hours of lectures in a 36 hour class, covering topics such as Normal and Lognormal Distributions; Distributions of Means and Errors in Exposure Measurements; Confidence and Tolerance Limits; and Selection of Workers and Times to be Sampled.

* Chaired the planning committee for the April 2004 short course by C Davis on Statistical Methods for the Analysis of Repeated Measurements. Served on the planning committees for: the February 1996 short course by R. Helms on Mixed Models, the March 1993 short course by R. Hogg on Total Quality Management; the April 1992 U.S. Public Health Service Professional meeting; the March 1992 ENAR Biometrics meeting; and the November 1990 Ohio Statistics Conference.

* Served as discussion leader for a round table discussion "SAS/Graph on the PC: User Experiences" held at the 15th annual SAS Users Group International conference, April 1990, in Nashville, TN.

* Assisted in the preparation of a poster "Statistics at NIOSH" which was on display at the Hamilton County Public Library (main branch) during November 1989 to commemorate the 150th anniversary of the American Statistical Association.

* Participant in a workshop: "Methods for semen studies in humans," held in Washington DC, October 1989. I led discussion in three areas: "Assessing variability between and within individuals"; "Design considerations for parameters measured on individual cells"; and "Recoding continuous semen quality data as a binary response: the application of tolerance intervals to morphometry data." I also served as rapporteur for the statistical methods section that included these three discussions.

* Programmed and tested in 1987 with LM Quinn a set of Turbo Pascal programs (SAMPLE, SAMSTAT, CONFINT, CHART, and HISTGRAM) that illustrate the random sampling process on real world data sets. In my Business Statistic courses, I have run these programs as part of my lectures on the Central Limit Theorem, on the effect of sample size on sampling error, and on the meaning of confidence in a 95% confidence interval. In addition, I have used these programs in a presentation, "Simulating Random Sampling" (see above) and in "Using some Turbo Pascal programs to simulate random sampling in the classroom" (also see above).

* Programmed, documented, and tested in 1986 a series of benchmarks written in BASIC and Pascal (NUMACC.BAS and NUMACC.PAS) to evaluate numerical accuracy.

Volunteer activities

* Head of the St. Paul's Movie Group, December 2004 to present, a group that offers a social outlet for members of St. Pauls United Methodist Church in Lenexa, KS. The Movie Group meets on the second Friday of each month to see a first run movie and afterwards visits a nearby restaurant to discuss the movie. As head of the group, I maintain a mailing list of members, select an appropriate movie, announce the choice, and collect RSVPs. The Movie Group also hosts an Academy Awards party every year.

* Performer with the Back Porch Cloggers, December 1999 to May 2006, a group that performed Appalachian Clogging. We would regularly entertain at various local retirement homes and nursing facilities.

* Tutored for the Adult Basic Literacy program, March 2000 to December 2001, two hours per week. I provided assistance to adults who were studying for their GED degree.

* Tutored students at Longfellow Elementary School, November 1999 to March 2000, one hour per week. I provided assistance to a third grade student in various academic areas, mostly math.

* Edited the Red Oak Hills Homeowners Association newsletter, November 1998 to April 2002. This newsletter appears four or more times a year and highlights information of interest to the 275 home owners in Red Oak Hills.

* Keyperson for the Combined Federal Campaign, Fall 1989. I passed out pledge forms for the Combined Federal Campaign, a program for federal employees similar to United Way, and answered questions about this program.

* Assisted in the proctoring and grading of tests in a Math contest sponsored by Miami University, Middletown, March 1988.

* Selected as faculty advisor for Bowling Green State University Chess Club, Fall 1984 to Spring 1987.

* Computerized the mailing list with DK Wild for the Wood County Humane Society using PC-FILE III, Spring 1985.

## Hobbies and Interests

Appalachian Clogging, Bridge, Cats, Chess, Computers, Contra Dancing, Crossword Puzzles, Languages, Travel, Volleyball, Walking.

## Publications

The definitive list of publications is available at https://www.ncbi.nlm.nih.gov/myncbi/browse/collection/48071026/?sort=date&direction=descending

* Barker JP, Simon SD, Dubin J. The Methodology of Clinical Studies Used by the FDA for Approval of High-Risk Orthopaedic Devices. The Journal of bone and joint surgery. American volume. 2017; 99(9):711-719. PMID: 28463914

* Parthiban A, Levine JC, Nathan M, Marshall JA, Shirali GS, Simon SD, Colan SD, Newburger JW, Raghuveer G. Implementation of a Quality Improvement Bundle Improves Echocardiographic Imaging after Congenital Heart Surgery in Children. Journal of the American Society of Echocardiography : official publication of the American Society of Echocardiography. 2016; 29(12):1163-1170.e3. PMID: 27742240

* Jiang Y, Guarino P, Ma S, Simon S, Mayo MS, Raghavan R, Gajewski BJ. Bayesian accrual prediction for interim review of clinical studies: open source R package and smartphone application. Trials. 2016; 17(1):336. PMID: 27449769, PMCID: PMC4957321

* Prindaville B, Simon SD, Horii KA. Dermatology-related outpatient visits by children: Implications for workforce and pediatric education. Journal of the American Academy of Dermatology. 2016; 75(1):228-9. PMID: 27317526

* Berkley-Patton J, Thompson CB, Moore E, Hawes S, Simon S, Goggin K, Martinez D, Berman M, Booker A. An HIV Testing Intervention in African American Churches: Pilot Study Findings. Annals of behavioral medicine : a publication of the Society of Behavioral Medicine. 2016; 50(3):480-5. NIHMSID: NIHMS752446 PMID: 26821712, PMCID: PMC5026504

* Baker JM, Pace HA, Ladesich JB, Simon SD. Evaluation of the Impact of Corticosteroid Dose on the Incidence of Hyperglycemia in Hospitalized Patients with an Acute Exacerbation of Chronic Obstructive Pulmonary Disease. Hospital pharmacy. 2016; 51(4):296-304. PMID: 27303077, PMCID: PMC4896332

* Parthiban A, Levine JC, Nathan M, Marshall JA, Shirali GS, Simon SD, Colan SD, Newburger JW, Raghuveer G. Impact of Variability in Echocardiographic Interpretation on Assessment of Adequacy of Repair Following Congenital Heart Surgery: A Pilot Study. Pediatric cardiology. 2016; 37(1):144-50. PMID: 26358473

* Anderst J, Teran P, Dowd MD, Simon S, Schnitzer P. The association of the rapid assessment of supervision scale score and unintentional childhood injury. Child maltreatment. 2015; 20(2):141-5. PMID: 25601937

* Knapp JF, Simon SD, Sharma V. Does active dissemination of evidence result in faster knowledge transfer than passive diffusion?: An analysis of trends of the management of pediatric asthma and croup in US emergency departments from 1995 to 2009. Pediatric emergency care. 2015; 31(3):190-6. PMID: 24694945

* Jiang Y, Simon S, Mayo MS, Gajewski BJ. Modeling and validating Bayesian accrual models on clinical data and simulations using adaptive priors. Statistics in medicine. 2015; 34(4):613-29. NIHMSID: NIHMS637332 PMID: 25376910, PMCID: PMC4314351

* Big Data Analysis for Bioinformatics and Biomedical Discoveries. Simon SD. Ye SQ, editor. New York, NY: Chapman & Hall; 2015. Chapter 3, R for Big Data Analysis
 
* Patterson ME, Marken P, Zhong Y, Simon SD, Ketcherside W. Comprehensive electronic medical record implementation levels not associated with 30-day all-cause readmissions within Medicare beneficiaries with heart failure. Applied clinical informatics. 2014; 5(3):670-84. PMID: 25298808, PMCID: PMC4187085

* Berkley-Patton JY, Moore E, Berman M, Simon SD, Thompson CB, Schleicher T, Hawes SM. Assessment of HIV-related stigma in a US faith-based HIV education and testing intervention. Journal of the International AIDS Society. 2013; 16(3 Suppl 2):18644. PMID: 24242259, PMCID: PMC3833192

* Shah A, Kumar S, Simon SD, Singh DP, Kumar A. HIV gp120- and methamphetamine-mediated oxidative stress induces astrocyte apoptosis via cytochrome P450 2E1. Cell death & disease. 2013; 4:e850. PMID: 24113184, PMCID: PMC3824683

* Knapp JF, Simon SD, Sharma V. Variation and trends in ED use of radiographs for asthma, bronchiolitis, and croup in children. Pediatrics. 2013; 132(2):245-52. PMID: 23878045

* Gajewski BJ, Simon SD, Carlson SE. On the Existence of Constant Accrual Rates in Clinical Trials and Direction for Future Research. International journal of statistics and probability. 2012; 1(2):p43. NIHMSID: NIHMS389648 PMID: 23869201, PMCID: PMC3712523

* Patterson ME, Marken PA, Simon SD, Hackman JL, Schaefer RS. Associations between the concurrent use of clinical decision support and computerized provider order entry and the rates of appropriate prescribing at discharge. Applied clinical informatics. 2012; 3(2):186-96. PMID: 23646071, PMCID: PMC3613019

* Simon SD. Tackling conflicts of interest. Subjective editorials and clinical reviews require proof of objectivity. BMJ (Clinical research ed.). 2011; 343:d5601. PMID: 21896589

* Gilman AL, Jacobsen C, Bunin N, Levine J, Goldman F, Bendel A, Joyce M, Anderson P, Rozans M, Wall DA, Macdonald TJ, Simon S, Kadota RP. Phase I study of tandem high-dose chemotherapy with autologous peripheral blood stem cell rescue for children with recurrent brain tumors: a Pediatric Blood and MarrowTransplant Consortium study. Pediatric blood & cancer. 2011; 57(3):506-13. PMID: 21744474

* Talib N, Onikul R, Filardi D, Simon S, Sharma V. Effective educational instruction in preventive oral health: hands-on training versus web-based training. Pediatrics. 2010; 125(3):547-53. PMID: 20123769

* Mercer AM, Teasley SL, Hopkinson J, McPherson DM, Simon SD, Hall RT. Evaluation of a breastfeeding assessment score in a diverse population. Journal of human lactation : official journal of International Lactation Consultant Association. 2010; 26(1):42-8. PMID: 19759350

* Miller MK, Denise Dowd M, Gratton MC, Cai J, Simon SD. Pediatric out-of-hospital emergency medical services utilization in Kansas City, Missouri. Academic emergency medicine : official journal of the Society for Academic Emergency Medicine. 2009; 16(6):526-31. PMID: 19426299

* Midyett LK, Grunt J, Simon SD. Noninvasive radial artery tonometry augmentation index and urinary albumin/creatinine levels in early adolescents with type 1 diabetes mellitus. Journal of pediatric endocrinology & metabolism : JPEM. 2009; 22(6):531-7. PMID: 19694200

* Jones BL, Abdel-Rahman SM, Simon SD, Kearns GL, Neville KA. Assessment of histamine pharmacodynamics by microvasculature response of histamine using histamine iontophoresis laser Doppler flowimetry. Journal of clinical pharmacology. 2009; 49(5):600-5. PMID: 19318525

* Knapp JF, Simon SD, Sharma V. Quality of care for common pediatric respiratory illnesses in United States emergency departments: analysis of 2005 National Hospital Ambulatory Medical Care Survey Data. Pediatrics. 2008; 122(6):1165-70. PMID: 19047229

* Graf WD, Kayyali HR, Alexander JJ, Simon SD, Morriss MC. Neuroimaging-use trends in nonacute pediatric headache before and after clinical practice parameters. Pediatrics. 2008; 122(5):e1001-5. PMID: 18838461

* Schurman JV, Danda CE, Friesen CA, Hyman PE, Simon SD, Cocjin JT. Variations in psychological profile among children with recurrent abdominal pain. Journal of clinical psychology in medical settings. 2008; 15(3):241-51. PMID: 19104969

* Gajewski BJ, Simon SD. A One-Hour Training Seminar on Bayesian Statistics for Nursing Graduate Students. The American Statistician. 2008 August 01; 62(3):190-4.

* Gajewski BJ, Simon SD, Carlson SE. Predicting accrual in clinical trials with Bayesian posterior predictive distributions. Statistics in medicine. 2008; 27(13):2328-40. PMID: 17979152

* Sati L, Ovari L, Bennett D, Simon SD, Demir R, Huszar G. Double probing of human spermatozoa for persistent histones, surplus cytoplasm, apoptosis and DNA fragmentation. Reproductive biomedicine online. 2008; 16(4):570-9. PMID: 18413066

* Adjei AA, Gaedigk A, Simon SD, Weinshilboum RM, Leeder JS. Interindividual variability in acetaminophen sulfation by human fetal liver: implications for pharmacogenetic investigations of drug-induced birth defects. Birth defects research. Part A, Clinical and molecular teratology. 2008; 82(3):155-65. PMID: 18232020

* Gaedigk A, Simon SD, Pearce RE, Bradford LD, Kennedy MJ, Leeder JS. The CYP2D6 activity score: translating genotype information into a qualitative measure of phenotype. Clinical pharmacology and therapeutics. 2008; 83(2):234-42. PMID: 17971818

* Authors' reply to letter regarding the original article "24-hour provoked excretion test for heavy metals in children with autism and typically developing  controls, a pilot study" Soden SE, Garrison CB, Lowry JA, Wasserman GS, Simon SD. Clinical Toxicology. 2008 January; 46(10):1098.

* Horii KA, Simon SD, Liu DY, Sharma V. Atopic dermatitis in children in the United States, 1997-2004: visit trends, patient and provider characteristics, and prescribing patterns. Pediatrics. 2007; 120(3):e527-34. PMID: 17766497

* Auron A, Warady BA, Simon S, Blowey DL, Srivastava T, Musharaf G, Alon US. Use of the multipurpose drainage catheter for the provision of acute peritoneal dialysis in infants and children. American journal of kidney diseases : the official journal of the National Kidney Foundation. 2007; 49(5):650-5. PMID: 17472847

* Auron A, Simon S, Andrews W, Jones L, Johnson S, Musharaf G, Warady BA. Prevention of peritonitis in children receiving peritoneal dialysis. Pediatric nephrology (Berlin, Germany). 2007; 22(4):578-85. PMID: 17216260

* Hampl SE, Carroll CA, Simon SD, Sharma V. Resource utilization and expenditures for overweight and obese children. Archives of pediatrics & adolescent medicine. 2007; 161(1):11-4. PMID: 17199061

* Abdel-Rahman SM, Simon S, Wright KJ, Ndjountche L, Gaedigk A. Tracking Trichophyton tonsurans through a large urban child care center: defining infection prevalence and transmission patterns by molecular strain typing. Pediatrics. 2006; 118(6):2365-73. PMID: 17142520

* Talebizadeh Z, Simon SD, Butler MG. X chromosome gene expression in human tissues: male and female comparisons. Genomics. 2006; 88(6):675-681. PMID: 16949791

* Ford SP, Leick-Rude MK, Meinert KA, Anderson B, Sheehan MB, Haney BM, Leeks SR, Simon SD, Jackson JK. Overcoming barriers to oxygen saturation targeting. Pediatrics. 2006; 118 Suppl 2:S177-86. PMID: 17079621

* Jackson JK, Ford SP, Meinert KA, Leick-Rude MK, Anderson B, Sheehan MB, Haney BM, Leeks SR, Simon SD. Standardizing nasal cannula oxygen administration in the neonatal intensive care unit. Pediatrics. 2006; 118 Suppl 2:S187-96. PMID: 17079622

* Dinakar C, Simon S. The link between the Hippocratic Oath and evidence-based medicine. Annals of allergy, asthma & immunology : official publication of the American College of Allergy, Asthma, & Immunology. 2006; 96(4):511-3. PMID: 16680920

* Abanses JC, Dowd MD, Simon SD, Sharma V. Impact of rapid influenza testing at triage on management of febrile infants and young children. Pediatric emergency care. 2006; 22(3):145-9. PMID: 16628094

* Beasley BW, Simon SD, Wright SM. A time to be promoted. The Prospective Study of Promotion in Academia (Prospective Study of Promotion in Academia). Journal of general internal medicine. 2006; 21(2):123-9. PMID: 16336619, PMCID: PMC1484667

* Simon SD. Statistical Evidence in Medical Trials. Oxford UK: Oxford University Press; 2006.

* Richmond W, Colgan G, Simon S, Stuart-Hilgenfeld M, Wilson N, Alon US. Random urine calcium/osmolality in the assessment of calciuria in children with decreased muscle mass. Clinical nephrology. 2005; 64(4):264-70. PMID: 16240897

* Thompson M, Simon SD, Sharma V, Alon US. Timing of follow-up voiding cystourethrogram in children with primary vesicoureteral reflux: development and application of a clinical algorithm. Pediatrics. 2005; 115(2):426-34. PMID: 15687452

* Hilgenfeld MS, Simon S, Blowey D, Richmond W, Alon US. Lack of seasonal variations in urinary calcium/creatinine ratio in school-age children. Pediatric nephrology (Berlin, Germany). 2004; 19(10):1153-5. PMID: 15309603

* Jackson JK, Biondo DJ, Jones JM, Moor PJ, Simon SD, Hall RT, Kilbride HW. Can an alternative umbilical arterial catheter solution and flush regimen decrease iatrogenic hemolysis while enhancing nutrition? A double-blind, randomized, clinical trial comparing an isotonic amino acid with a hypotonic salt infusion. Pediatrics. 2004; 114(2):377-83. PMID: 15286220

* George ME, Sharma V, Jacobson J, Simon S, Nopper AJ. Adverse effects of systemic glucocorticosteroid therapy in infants with hemangiomas. Archives of dermatology. 2004; 140(8):963-9. PMID: 15313812

* Hellerstein S, Berenbom M, DiMaggio S, Erwin P, Simon SD, Wilson N. Comparison of two formulae for estimation of glomerular filtration rate in children. Pediatric nephrology (Berlin, Germany). 2004; 19(7):780-4. PMID: 15071771

* Ekekezie II, Thibeault DW, Simon SD, Norberg M, Merrill JD, Ballard RA, Ballard PL, Truog WE. Low levels of tissue inhibitors of metalloproteinases with a high matrix metalloproteinase-9/tissue inhibitor of metalloproteinase-1 ratio are present in tracheal aspirate fluids of infants who develop chronic lung disease. Pediatrics. 2004; 113(6):1709-14. PMID: 15173495

* Grunt JA, Midyett LK, Simon SD, Lowe L. When should cranial magnetic resonance imaging be used in girls with early sexual development? Journal of pediatric endocrinology & metabolism : JPEM. 2004; 17(5):775-80. PMID: 15237713

* Murphy WJ, Franks JR, Berger EH, Behar A, Casali JG, Dixon-Ernst C, Krieg EF, Mozo BT, Royster JD, Royster LH, Simon SD, Stephenson C. Development of a new standard laboratory protocol for estimation of the field attenuation of hearing protection devices: sample size necessary to provide acceptable reproducibility. The Journal of the Acoustical Society of America. 2004; 115(1):311-23. PMID: 14759024

* Miller-Hansen DR, Nelson PB, Widen JE, Simon SD. Evaluating the benefit of speech recoding hearing aids in children. American journal of audiology. 2003; 12(2):106-13. PMID: 14964326

* Portnoy JM, Simon SD. Is 3-mm less drowsiness important? Annals of allergy, asthma & immunology : official publication of the American College of Allergy, Asthma, & Immunology. 2003; 91(4):324-5. PMID: 14582809

* Murphy JV, Torkelson R, Dowler I, Simon S, Hudson S. Vagal nerve stimulation in refractory epilepsy: the first 100 patients receiving vagal nerve stimulation at a pediatric epilepsy center. Archives of pediatrics & adolescent medicine. 2003; 157(6):560-4. PMID: 12796236

* Santos SR, Carroll CA, Cox KS, Teasley SL, Simon SD, Bainbridge L, Cunningham M, Ott L. Baby boomer nurses bearing the burden of care: A four-site study of stress, strain, and coping for inpatient registered nurses. The Journal of nursing administration. 2003; 33(4):243-50. PMID: 12690256

* Sharma V, Dowd MD, Swanson DS, Slaughter AJ, Simon SD. Influence of the news media on diagnostic testing in the emergency department. Archives of pediatrics & adolescent medicine. 2003; 157(3):257-60. PMID: 12622675

* De Jonge CJ, Centola GM, Reed ML, Shabanowitz RB, Simon SD, Quinn P. Human sperm survival assay as a bioassay for the assisted reproductive technologies laboratory. Journal of andrology. 2003; 24(1):16-8. PMID: 12514073

* Hall RT, Mercer AM, Teasley SL, McPherson DM, Simon SD, Santos SR, Meyers BM, Hipsh NE. A breast-feeding assessment score to evaluate the risk for cessation of breast-feeding by 7 to 10 days of age. The Journal of pediatrics. 2002; 141(5):659-64. PMID: 12410194

* Carroll CA, Cox KS, Santos SR, Simon SD. Using standard desk-top tools to monitor medical error rates. Seminars for nurse managers. 2002; 10(2):95-9. PMID: 12092273

* Grunt JA, Schwartz ID, Simon SD, Howard CP. Growth Hormone Responsiveness in Two Groups of Children With Significantly Short Stature. The Endocrinologist. 2002; 12:58-65.

* Sharma V, Dowd MD, Slaughter AJ, Simon SD. Effect of rapid diagnosis of influenza virus type a on the emergency department management of febrile infants and toddlers. Archives of pediatrics & adolescent medicine. 2002; 156(1):41-3. PMID: 11772189

* Simon SD. Is the randomized clinical trial the gold standard of research? Journal of andrology. 2001; 22(6):938-43. PMID: 11700857

* Hellerstein S, Simon SD, Berenbom M, Erwin P, Nickell E. Creatinine excretion rates for renal clearance studies. Pediatric nephrology (Berlin, Germany). 2001; 16(8):637-43. PMID: 11519893

* Simon SD. Understanding the odds ratio and the relative risk. Journal of andrology. 2001; 22(4):533-6. PMID: 11451349

* Barnes C, Tuck J, Simon S, Pacheco F, Hu F, Portnoy J. Allergenic materials in the house dust of allergy clinic patients. Annals of allergy, asthma & immunology: official publication of the American College of Allergy, Asthma, & Immunology. 2001; 86(5):517-23. PMID: 11379802

* Simon SD. Interpreting positive studies. Journal of andrology. 2001; 22(3):358-9. PMID: 11330635

* So NP, Osorio AV, Simon SD, Alon US. Normal urinary calcium/creatinine ratios in African-American and Caucasian children. Pediatric nephrology (Berlin, Germany). 2001; 16(2):133-9. PMID: 11261680

* Simon SD. Interpreting negative studies. Journal of andrology. 2001; 22(1):13-6. PMID: 11191078

* Sharma V, Simon SD, Bakewell JM, Ellerbeck EF, Fox MH, Wallace DD. Factors influencing infant visits to emergency departments. Pediatrics. 2000; 106(5):1031-9. PMID: 11061772

* Grajewski B, Cox C, Schrader SM, Murray WE, Edwards RM, Turner TW, Smith JM, Shekar SS, Evenson DP, Simon SD, Conover DL. Semen quality and hormone levels among radiofrequency heater operators. Journal of occupational and environmental medicine. 2000; 42(10):993-1005. PMID: 11039163

* Hall RT, Simon S, Smith MT. Readmission of breastfed infants in the first 2 weeks of life. Journal of perinatology : official journal of the California Perinatal Association. 2000; 20(7):432-7. PMID: 11076327

* Portnoy J, Landuyt J, Pacheco F, Flappan S, Simon S, Barnes C. Comparison of the Burkard and Allergenco MK-3 volumetric collectors. Annals of allergy, asthma & immunology : official publication of the American College of Allergy, Asthma, & Immunology. 2000; 84(1):19-24. PMID: 10674560

* Gaedigk A, Gotschall RR, Forbes NS, Simon SD, Kearns GL, Leeder JS. Optimization of cytochrome P4502D6 (CYP2D6) phenotype assignment using a genotyping algorithm based on allele frequency data. Pharmacogenetics. 1999; 9(6):669-82. PMID: 10634130

* Kliethermes PA, Cross ML, Lanese MG, Johnson KM, Simon SD. Transitioning preterm infants with nasogastric tube supplementation: increased likelihood of breastfeeding. Journal of obstetric, gynecologic, and neonatal nursing : JOGNN. 1999; 28(3):264-73. PMID: 10363538

* Srivastava T, Simon SD, Alon US. High incidence of focal segmental glomerulosclerosis in nephrotic syndrome of childhood. Pediatric nephrology (Berlin, Germany). 1999; 13(1):13-8. PMID: 10100283

* Schrader SM, Langford RE, Turner TW, Breitenstein MJ, Clark JC, Jenkins BL, Lundy DO, Simon SD, Weyandt TB. Reproductive function in relation to duty assignments among military personnel. Reproductive toxicology (Elmsford, N.Y.). 1998; 12(4):465-8. PMID: 9717697

* Moorman WJ, Skaggs SR, Clark JC, Turner TW, Sharpnack DD, Murrell JA, Simon SD, Chapin RE, Schrader SM. Male reproductive effects of lead, including species extrapolation for the rabbit model. Reproductive toxicology (Elmsford, N.Y.). 1998; 12(3):333-46. PMID: 9628556

* Sivak A, Niemeier R, Lynch D, Beltis K, Simon S, Salomon R, Latta R, Belinky B, Menzies K, Lunsford A, Cooper C, Ross A, Bruner R. Skin carcinogenicity of condensed asphalt roofing fumes and their fractions following dermal application to mice. Cancer letters. 1997; 117(1):113-23. PMID: 9233840

* Weyandt TB, Schrader SM, Turner TW, Simon SD. Semen analysis of military personnel associated with military duty assignments. Reproductive toxicology (Elmsford, N.Y.). 1996; 10(6):521-8. PMID: 8946566

* Combining reproductive studies of men exposed to 2-ethoxyethanol to increase statistical power Schrader SM, Turner TW, Ratcliffe JW, Welch LS, Simon SD. Occupational Hygiene. 1996; 2:411-5.

* Schrader SM, Ayers-Cumbo M, Turner TW, Simon SD, Ratcliffe J, Welch L, Grajewski B, Weyandt T. Semen quality across populations. Molecular Andrology. 1995; 7:105-21.

* A biological monitoring method for o-Toluidine and Aniline in urine using high performance liquid chromatography with electrochemical detection Brown KK, Teass AW, Simon SD, Ward EM. Applied Occupational and Environmental Hygiene. 1995; 10(6):557-65.

* Schrader SM, Turner TW, Breitenstein MJ, Simon SD. Measuring male reproductive hormones for occupational field studies. Journal of occupational medicine. : official publication of the Industrial Medical Association. 1993; 35(6):574-6. PMID: 8331437

* Knecht EA, Moorman WJ, Clark JC, Hull RD, Biagini RE, Lynch DW, Boyle TJ, Simon SD. Pulmonary reactivity to vanadium pentoxide following subchronic inhalation exposure in a non-human primate animal model. Journal of applied toxicology : JAT. 1992; 12(6):427-34. PMID: 1452976

* Platek SF, Riley RD, Simon SD. The classification of asbestos fibres by scanning electron microscopy and computer-digitizing tablet. The Annals of occupational hygiene. 1992; 36(2):155-71. PMID: 1326908

* Stettler LE, Platek SF, Riley RD, Mastin JP, Simon SD. Lung particulate burdens of subjects from the Cincinnati, Ohio urban area. Scanning microscopy. 1991; 5(1):85-92; discussion 92-4. PMID: 1647057

* Schrader SM, Turner TW, Simon SD. Longitudinal study of semen quality of unexposed workers. Sperm motility characteristics. Journal of andrology. 1991; 12(2):126-31. PMID: 2050580

* Schrader SM, Breitenstein MJ, Turner TW, Simon SD. Longitudinal study of semen quality of unexposed workers: seminal plasma characteristics. in Comparative spermatology 20 years after. Baccetti B, editor. New York NY: Serno Symposia Publications; 1991.

* Schrader SM, Turner TW, Simon SD. Sources of variation of the sperm penetration assay under field study conditions ARTA. 1991; 2(Suppl 4):63-74.

* Susten AS, Niemeier RW, Simon SD. In vivo percutaneous absorption studies of volatile organic solvents in hairless mice. II. Toluene, ethylbenzene and aniline. Journal of applied toxicology : JAT. 1990; 10(3):217-25.  PMID: 2380484

* Ryan AS, Wysong JL, Martinez GA, Simon SD. Duration of breast-feeding patterns established in the hospital. Influencing factors. Results from a national survey. Clinical pediatrics. 1990; 29(2):99-107. PMID: 2302909

* Schrader SM, Turner TW, Simon SD. Longitudinal study of semen quality of unexposed workers: sperm head morphometry. Journal of andrology. 1990; 11(1):32-9. PMID: 2312397

* Simon SD, Lesage JP. Assessing the accuracy of ANOVA calculations in statistical software. Computational Statistics and Data Analysis. 1990; 8(3):325-32.

* Small LH, Simon SD, Goldberg JS. Lexical stress and lexical access: homographs versus nonhomographs. Perception & psychophysics. 1988; 44(3):272-80. PMID: 3174358

* Schrader SM, Turner TW, Breitenstein MJ, Simon SD. Longitudinal study of semen quality of unexposed workers. I. Study overview. Reproductive toxicology (Elmsford, N.Y.). 1988; 2(3-4):183-90. PMID: 2980344

* Simon SD, Lesage JP. The impact of collinearity involving the intercept term on the numerical accuracy of regression. Computational Statistics and Data Analysis. 1988; 7:197-209.

* Simon SD, Lesage JP. Benchmarking numerical accuracy of statistical algorithms. Computational Statistics and Data Analysis. 1988; 7:197-209.

* Simon SD. How to illustrate numerical accuracy problems on any computer. Mathematics and Computer Education. 1987; 21(1):11-5.

* Simon SD. To err isn't only human. Computer Language. 1986; 3(3):11-15.

* Lesage JP, Simon SD. Numerical accuracy of statistical algorithms for microcomputers. Computational Statistics and Data Analysis. 1985; 3:47-57.

## Regional and national presentations 

Note I am not listing local presentations or presentations where I am not the first author. These are both too numerous to track accurately.

* Simon SD. "Good Computing Practices for Researchers" a 90 minute webinar presented for The Analysis Factor, November 2017.

* Simon SD. "LASSO Regression" a 90 minute webinar presented for The Analysis Factor, November 2016.

* Simon SD. "Cox Regression" a 90 minute webinar presented for The Analysis Factor, September 2016.

* Simon SD. "Introduction to Kaplan-Meier Curves" a 90 minute webinar presented for The Analysis Factor, April 2016.

* Simon SD. "A Gentle Introduction to Bayesian Data Analysis" a 90 minute webinar presented for The Analysis Factor, June 2015.
    
* Simon SD. "The Hedging Hyperprior," a 30 minute presentation for the regional Frontiers in Biostatistical Methods Conference, Kansas City MO, April 2015.
    
* Simon SD. "Setting Up and Running and Independent Statistical Consulting Practice," an invited four hour short course for the Conference on Statistical Practice, New Orleans LA, February 2015.

* Simon SD, Sanders S. "Statistics for Medical Librarians," an invited three hour short course for the Medical Librarians Association national meeting, Chicago IL, May 2014.

* Simon SD, "Selecting an Appropriate Sample Size" and "Conducting a Pilot Study" part of a three hour short course, Writing a CAM Grant, for the International Research Conference on Complementary Medicine, Miami FL, May 2014.

* Simon SD. "What is a P-Value?" an invited one hour short course for the Midwest Society of Pediatric Research, October 2013, Minneapolis MN.

* Simon SD, Sanders S. "Statistics for Medical Librarians," an invited three hour short course for the Medical Librarians Association national meeting, Seattle WA, May 2012.
    
* Simon SD, "Selecting an Appropriate Sample Size" and "Characteristics of a Good Statistical Consultant" part of a three hour short course, Writing a CAM Grant, for the International Research Conference on Complementary Medicine, Portland OR, May 2012.
    
* Simon SD. "Promoting Your Consulting Career," an invited two hour short course for the Conference on Statistical Practice, Orlando FL, February 2012.
    
* Simon SD. "How Independent Consulting is Different" part of a panel discussion, Statistical Consulting - Working Collaboratively Across Disciplines, for the Conference on Statistical Practice, Orlando FL, February 2012.

* Simon SD, Sanders S. "Statistics for Medical Librarians," an invited three hour short course for the Southeast Region of Medical Librarians Association annual meeting, Augusta GA, May 2012.

* Simon SD. "How Independent Consulting is Different" part of a panel discussion, Successful Statistical Consulting: The Practicalities, for the Joint Statistics Meeting, Miami Beach FL, August 2011.
    
* Simon SD. "Using Social Media to Promote Your Consulting Career," a lunchtime roundtable discussion for the Joint Statistics Meeting, Miami Beach FL, August 2011.

* Simon SD. "What is a P-Value?" an invited one hour short course for the Midwest Society of Pediatric Research, October 2010, Iowa City IA.

* Simon SD. "Discussion of Morphology Consensus Data," an invited two hour presentation including near real-time data analysis of classroom exercises for the Andrology Lab Workshop at the Andrology Society national meeting, April 2010, Houston, TX.

* Simon SD. "What Do All These Numbers Mean? Confidence Intervals and P-Values," an invited one hour short course for the Midwest Society of Pediatric Research, October 2009, Chicago IL.
    
* Simon SD. "Discussion of Morphology Consensus Data," an invited two hour presentation including near real-time data analysis of classroom exercises for the Andrology Lab Workshop at the Andrology Society national meeting, April 2009, Philadelphia, PA.

* Simon SD, Gajewski BJ "Bayesian tools for planning and monitoring accrual rates in clinical trials," an invited 30 minute oral presentation for the regional Frontiers in Biostatistical Methods Conference, April 2008, Kansas City, MO.
 
* Simon SD. "Assessing the Safety of Pediatric Treatments," an invited four hour short course for the Signal Detection and Risk Management conference, December 2007, Amsterdam, The Netherlands.
    
* Simon SD. "Control charts for continuous monitoring of the number needed to harm," an invited 35 minute oral presentation for the Signal Detection and Risk Management conference, December 2007, Amsterdam, The Netherlands.
    
* Simon SD. "Use of Diagnostic Tests for Making Clinical Decisions," an invited 30 minute oral presentation for the Annual Scientific Meeting of the American College of Allergy, Asthma & Immunology, November 2007, Dallas TX.
    
* Simon SD. "Open-Access Journals and Their Impact on Research and the Practice of Medicine" a one hour presentation for Grand Rounds, The Children's Mercy Hospital, October 2007, Kansas City, MO.
    
* Simon SD. "Statistical Evidence: Who Was Left Out," an invited 1.5 hour short course for the Midwest Society for Pediatric Research, October 2007, Indianapolis, IN.
    
* Simon SD, Gajewski B "Predicting Accrual in Clinical Trials: Bayesian Posterior Predictive Distributions," a contributed poster for the Joint Statistical Meetings, July/August 2007, Salt Lake City UT.

* Simon SD, Schrader SM. "Using Statistics to Monitor and Improve Quality," an invited three hour short course (I was responsible for two hours) for the 2007 Andrology Lab Workshop for the American Society for Andrology, April 2007, Tampa Bay, FL.
 
* Simon SD. "Control charts for continuous monitoring of the number needed to harm," an invited 35 minute oral presentation for the Signal Detection and Data Mining conference, December 2006, London, England.
    
* Simon SD. "Signal Detection Strategies for Paediatric Treatments," an invited 3 hour short course for the Signal Detection and Data Mining conference, December 2006, London, England.

* Simon SD. "Statistics Overview," an invited two hour presentation for the Midwest Society for Pediatric Research, October 2006, Indianapolis IN.

* Simon SD. "Statistical Evidence: Apples or Oranges?" an invited 1.5 hour short course for the Midwest Society for Pediatric Research, October 2005, St. Louis MO.
  
* Simon SD. "What Can Alternative Medicine Teach Us About Evidence-Based Medicine?" an invited 1.5 hour short course for the Midwest Society for Pediatric Research, October 2004, St. Louis MO.

* Simon SD. "Four Tips for Developing an Educational Web Site," a contributed poster presentation for the Joint Statistical Meetings, August 1998, Dallas TX.

* Simon SD. "Medical Statistics Case Studies on the Web, " a contributed 15 minute oral presentation for the Joint Statistical Meetings, August 1997, Anaheim CA.

* Simon SD. "Winning Ways of Laboratory Data Presentation: Analyzing and Presenting Your Laboratory Data," Course Co-director and Instructor for an 8 hour Andrology workshop. As an instructor, I presented two separate talks and supervised several computer exercises. American Society for Andrology, April 1996, Minneapolis, MN.
   
* Simon SD, Schrader SM. "Statistical Methods and Experimental Design in the Reproductive Laboratory," a contributed oral presentation for the Annual Meeting of the American Society for Reproductive Medicine, October 1995, Seattle WA.
  
* Simon SD, Schrader SM, Turner TW. "Statistical Methods for Human Reproductive Toxicology Research," an invited presentation at the Biometric Society meeting, April 1994, Cleveland OH.
  
* Simon SD, Schrader SM, Turner TW. "The Use of Tolerance Intervals for Assessing Male Reproductive Potential," a contributed 15 minute presentation for the Joint Statistical Meetings, August 1989, Washington, DC.

* Simon SD, Lesage JP. "Studying Numerical Accuracy as a Controlled Experiment," a contributed presentation for the Conference on the Interface Between Computer Science and Statistics, March 1987, Philadelphia PA and published in the conference proceedings.

* Simon SD, Quinn LM. "Using Some Turbo Pascal Programs to Simulate Random Sampling in the Classroom," a contributed presentation for the Winter Conference of the American Statistical Association, January 1987, Orlando FL. There is a very similar talk by the same authors, "Simulating Random Sampling," a contributed presentation for the Thirteenth Annual Mathematics and Statistics conference, September 1985, Oxford OH.

* Simon SD. "The Median Star: an Alternative to the Tukey Resistant Line," a contributed 15 minute presentation for the Joint Statistical Meetings, August 1986, Chicago IL and published in the Proceedings of the Statistical Computing Section.

* Simon SD. "Quick Estimates of Slope Based on the Cox and Stuart Test for Trend," a contributed 15 minute presentation for the Joint Statistical Meetings, August 1985, Las Vegas NV.

* Simon SD, Lesage JP. "The Impact of Centering and Scaling on Numerical Accuracy of Regression Algorithms," a contributed presentation for the Applied Simulation and Modeling conference, June 1985, Montreal Canada and published in the conference proceedings.

## Computer experience
* Bibliographic software: EndNotes, Knowledge Finder, Zotero.
* Database software: Microsoft Access, Microsoft SQL Server, Oracle, PC-File, SQLite.
* Graphics software: ACDSee, Metafile Companion, Photoshop Elements, SigmaPlot.
* Internet systems: File Transfer Protocol, Gopher, Telnet, USENET, WordPress, World Wide Web.
* Mathematical software: MathCAD, Mathematica, MathType.
* Presentation software: Powerpoint.
* Programming languages: BASIC, C, FORTRAN, Pascal, Perl, PL/1, Visual BASIC.
* Spreadsheets: Excel, Lotus 1-2-3, SuperCalc.
* Statistical software: AMOS, BMDP, IMSL, JMP, LogXact, MINITAB, nQuery Advisor, OpenBUGS, R, RATS, S-Plus, S-Plus/Wavelets, SAS, Stan, SPIDA, SPSS, STATA, Statgraphics, StatXact, Systat, WinBUGS.
* Utility software: DBMS/COPY, Norton Anti-virus, TextPad, WinZip.
* Word processing: Word, Word Perfect.
* Other experience: I have supervised the implementation of a Novell Local Area Network and Microsoft SQL Server, a client-server database, both for a division of 100+ employees. I have authored web pages using Adobe Acrobat, Adobe Dreamweaver, Camtasia Studio, and Microsoft Front Page. I have used and taught IBM mainframe Job Control Language, including tape and disk I/O.

## Professional conferences attended

* Conference on Statistical Practice, February 2015, New Orleans, LA.
* Joint Statistical Meetings, August 2014, Boston, MA.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2014, Kansas City, MO.
* Joint Statistical Meetings, August 2013, Montreal, Canada.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2013, Kansas City, MO.
* KC Bioresearch Summit, November 2012, Overland Park, KS.
* Joint Statistical Meetings, August 2012, San Diego, CA.
* Frontiers/KCALSI Research Symposium, May 2012, Kansas City, MO.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2012, Kansas City, MO.
* Conference on Statistical Practice, February 2012, Orlando, FL.
* Fall Technical Conference, October 2011, Kansas City, MO.
* Joint Statistical Meetings, August 2011, Miami Beach, FL.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2011, Kansas City, MO.
* Joint Statistical Meetings, August 2010, Vancouver, Canada.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2010, Kansas City, MO.
* Joint Statistical Meetings, August 2009, Washington, DC.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2009, Kansas City, MO.
* Bayesian Biostatistics Conference, January 2009, Houston, TX.
* Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, April 2008, Kansas City, MO.
* Joint Statistical Meetings, August 2007, Salt Lake City, UT.
* Joint Statistical Meetings, August 2006, Seattle, WA.
* Eighteenth Annual Applied Statistics in Agriculture, April 2006, Manhattan, KS.
* Fifth Annual Kansas City Life Sciences Research Day, April 2006, Kansas City, MO.
* Joint Statistical Meetings, August 2005, Minneapolis, MN.
* Fourth Annual Kansas City Life Sciences Research Day, April 2005, Overland Park, KS.
* Joint Statistical Meetings, August 2004, Toronto, CA.
* Bridging the Gap Between Eastern & Western Medicine, January 2004, Kansas City, MO.
* Joint Statistics Meetings, August 2003, San Francisco, CA.
* ENAR Biometric Society Meeting, March 2003, Tampa FL.
* Second Annual Kansas City Life Sciences Research Day, March 2003, Kansas City, MO.
* A Higher Standard: The Ethics of Clinical Research, September 2002, Kansas City, MO.
* Seventh Annual Clinical Research Symposium: Focus on Pediatric Pain, September 2002, Kansas City, MO.
* Joint Statistical Meetings, August 2002, New York NY.
* Joint Statistical Meetings, August 2001, Atlanta GA.
* Joint Statistical Meetings, August 2000, Indianapolis IN.
* Fourth Annual Clinical Research Symposium, June 2000, Kansas City MO.
* NIH Regional Seminar on Program Funding and Grants Administration, June 2000, Kansas City MO
* Conference on Applied Statistics in Agriculture, May 2000, Manhattan KS
* The 7th National Research Utilization Conference: Evidence-Based Interventions for Symptom Management, April 2000, Iowa City IA
* Toastmasters District 22 Spring Conference, April 2000, Kansas City MO
* Joint Statistical Meetings, August 1999, Baltimore MD
* NIH Regional Seminar on Grants Administration, July 1999, Madison WI
* Fourth Annual Clinical Research Symposium, June 1999, Kansas City, MO
* Research Involving Infants, Children, and Adolescents: Issues and Ethics for the 21st Century, April 1999, Kansas City MO
* The Elements of Clinical Research: An Overview, October 1998, Kansas City, MO
* Joint Statistical Meetings, August 1998, Dallas TX
* Global Statistical Challenges and Strategies in the Pharmaceutical Industry, March 1998, Hilton Head SC
* Joint Statistical Meetings, August 1997, Anaheim CA
* Fourth International Applied Statistics in Industry conference, June 1997, Kansas City MO
* Second Annual Clinical Research Symposium, June 1998, Kansas City, MO
* Eastern North America Region Biometric Society Meeting, March 1997, Memphis TN
* SAS Users Group International Conference, March 1997, San Diego CA
* Joint Statistical Meetings, August 1996, Chicago IL
* Midwest SAS Users Group Meeting, October 1995, Cleveland OH
* Ohio Statistics Conference, November 1994, Oxford OH
* Total Quality Management in Government Conference, September 1994, Cincinnati OH
* Joint Statistical Meetings, August 1994, Toronto, Ontario
* Midwest SAS Users Group Conference, August 1993, Indianapolis IN
* Deming Users Group Conference, August 1993, Cincinnati OH
* Statistical Methods for Multi-Source Data, January 1993, Atlanta GA
* Midwest SAS Users Group Conference, October 1992, Kansas City MO
* Joint Statistical Meetings, August 1992, Atlanta GA
* U.S. Public Health Service Professional Meeting, April 1992, Cincinnati OH
* Eastern North America Region Biometric Society Meeting, March 1992, Cincinnati OH
* Statistics and Quality Conference, October 1991, Lexington OH
* State Based Occupational Health and Safety Activities, September 1991, Cincinnati OH
* Joint Statistical Meetings, August 1990, Anaheim CA
* SAS Users Group International Conference, April 1990, Nashville TN
* Total Quality Management in Government Conference, March 1990, Cincinnati OH
* SAS Users Group International Conference, April 1989, San Francisco CA
* Winter Meeting of the American Statistical Association, January 1988, San Antonio TX
* MINITAB Users Group meeting, January 1987, Orlando FL
* Interface between Computer Science and Statistics, March 1985, Lexington KY

## Training classes attended

* Network Analysis in Cross-sectional Data Using R (E Fried), 2 contact hours, December 2017, Webinar.
* Databases in the tidyverse (B Baumer, N Horton), 1.5 contact hours, November 2017, Webinar.
* Use of Historical Data in Designed Experiments (B Neuenschwander, H Schmidli), 1.5 contact hours, April 2014, Webinar.
* DSMBs DMCs (S Evans), 1.5 contact hours, September 2013, Webinar.
* Practical Software Engineering for Statisticians (M Stokely), 4 contact hours, August 2013, Montreal Canada.
* Design and Analysis of Non-inferiority Trials (B Wiens), 4 contact hours, August 2013, Montreal Canada.
* Advancing Faculty Development and Scholarly Careers in Quality Improvement, 1.5 contact hours, April 2013, Webinar.
* Impact of Phase 2 Dose-finding Study Design on Phase 3 Probability of Success and Net Present Value, March 2012, Webinar.
* Bayesian Methods for Non-inferiority Tests and Sample Size Determinations, November 2011, Webinar.
* Applied Survival Analysis (S May), 6 contact hours, October 2008.
* NLM Gateway and ClincalTrials.gov, 6 contact hours, April 2008.
* PubMed training, 6 contact hours, April 2008.
* Quantitative Trait Locus (QTL) Mapping (R Doerge), 6 contact hours, April 2007.
* Grants 101: Essential Information, 24 contact hours, August 2006.
* Writing Winning Grants Workshop (K Gary and D Morrison), 4 contact hours, April 2006.
* Bayesian Clinical Trials (S Berry), 8 contact hours, April 2006.
* Analysis of Gene Expression Data (T Speed, B Bolstad, YHJ Yang, J Wettenhall), 16 contact hours, August 2005.
* Exploration and Analysis of DNA Microarray Data (J Cabrera), four week web based class with approximately 5-15 hours per week of work, October 2005.
* Advanced Excel for the Power User, 8 contact hours, June 2005.
* Excel: Beyond Mere Basics, 8 contact hours, June 2005.
* Bootstrap Methods and Permutation Tests for Doing and Teaching Statistics (T Hesterberg), 4 contact hours, August 2004.
* Successful Data Mining in Practice (R De Veaux), 16 contact hours, August 2003.
* Linear Mixed Models in SPSS, 2 contact hours, August 2003.
* Statistical Methods and Software for the Analysis of DNA Microarray Experiments (S Dudoit, R Irizarry), 4 contact hours, March 2003.
* Introduction to Molecular Biology and Bioinformatics Studies for Analysts (E Lazaridis), 4 contact hours, August 2002.
* Statistical Methods for Microarray Studies (E Lazaridis), 4 contact hours, August 2002.
* How to Practice Evidence Based Medicine, 16 contact hours, September 2001.
* Model Based Clustering (A Raftery, C Fraley), 16 contact hours, August 2001.
* Research Principles III (Corporate Compliance and Genetic Testing), 2 contact hours, May 2001.
* Responsible Conduct of Research: What Every Faculty Researcher Needs to Know: Experimental Design, Data Selection and Data Management, 1 contact hour, November 2000.
* Research Principles: Part I, 4 contact hours, September 2000.
* Conversational Database: A Traveler's Guide to Database Theory and Common Query Languages (R Grasser), 4 contact hours, August 2000.
* Wavelets in the Real World: Concepts and Applications (R Ogden), 4 contact hours, August 2000.
* Statistical Searches for Disease Genes (B Weir), 8 contact hours, August 1999
* An Introduction to Generalized Linear Mixed Models (C McCulloch), 16 contact hours, August 1999
* The Basics of Web Site Design, 8 contact hours, November 1999
* Step-by-Step: Static HTML to a High Performance Web Farm, 3 contact hours, June 1999
* Writing Winning Grants Workshop (D Morrison), 5 contact hours, April 1999
* Sample Size and Power Determination in Medical Research and Clinical Trials (JD Elashoff), 3.5 contact hours, March 1998
* Microsoft Outlook 97, 8 contact hours, November 1997
* Early Stopping of Clinical Trials (G Lan), 4 contact hours, August 1997
* Analysis of Functional Data (B Silverman and JO Ramsey), 16 contact hours, August 1997
* Advanced Access 7.0, 8 contact hours, June 1997
* Intermediate Access 7.0, 8 contact hours, April 1997
* Access 7.0: Tables, 4 contact hours, March 1997
* Bayes and Empirical Bayes Methods for Biostatistical Data Analysis (B Carlin and T Louis), 8 contact hours, March 1997
* Great Explanations: Listening Skills, 2 contact hours, January 1997
* Sampling-Based Methods for Bayesian and Likelihood Inference (M Tanner and I Hoeschele), 16 contact hours, August 1996
* Learning to Fly with Mixed Models, 8 contact hours, February 1996
* Building Leadership Skills, 16 contact hours, September 1995
* Nonlinear Mixed Effects Models in S-Plus (D Bates), 16 contact hours, August 1995
* Government Performance and Results Act of 1993. Managing for Results: A Strategy for Successful Change in Government, 16 contact hours, August 1995
* Advanced Project Officer Training, 20 contact hours, April 1995
* Statistical Models in S-Plus, 24 contact hours, March 1995
* Win-Win Communications, 16 contact hours, November 1994
* Managing Diversity, 8 contact hours, October 1994
* Classification and Position Management, 16 contact hours, July 1994
* HIV/AIDS Sensitivity, 4 contact hours, July 1994
* Employee Relations, 16 contact hours, April 1994
* Labor Relations, 8 contact hours, April 1994
* Government Credit Card Rules and Regulations, 8 contact hours, April 1994
* Continuous Quality Improvement (R Hogg), 8 contact hours, March 1994
* Process Action Team Leader, 36 contact hours, February 1994
* Basic Project Officers Training, 16 contact hours, January 1994
* Principles of Total Quality Management, 20 contact hours, November 1993
* S-plus Basic and Advanced Training, 40 contact hours, September 1993
* Sexual Harassment Awareness, 8 contact hours, May 1993
* The Analysis of Longitudinal Data (K Liang and S Zeger), 16 contact hours, January 1993
* Effective Scientific Visualization (E Tufte), 16 contact hours, December 1992
* Introduction to OS/2 2.0, 4 contact hours, November 1992
* Introduction to Microsoft Windows, 4 contact hours, October 1992
* Categorical Data Analysis (J Fleiss), 20 contact hours, September 1992
* Reproductive and Developmental Epidemiology: Emerging Approaches, 8 contact hours, September 1992
* Multivariable Modeling of Epidemiologic Data, 32 contact hours, October 1991
* Commissioned Corps Orientation, 12 contact hours, September 1990
* Categorical Data Analysis (A Agresti and C Chuang-Stein), 8 contact hours, August 1990
* Generalized Additive Models (T Hastie and R Tibshirani), 8 contact hours, August 1990
* Principles and Practices of Supervision: Part II, 20 contact hours, April 1990
* Analysis of Binary Data (D Cox and E Snell), 16 contact hours, August 1989
* Practical Biological Modeling (D Allen and J Matis), 8 contact hours, March 1989
* Principles and Practices of Supervision: Part I, 36 contact hours, May 1988
* Risk Control in Clinical Trials for Efficacy (A Johnson), 8 contact hours, January 1988
* Analysis of Complex Surveys (J Landis and J Lepkowski), 40 contact hours, August 1987
* Assembly Language Programming (Audit), 48 contact hours, September 1986
* Introduction to the Bootstrap (B Efron and R Tibshirani), 8 contact hours, August 1985
* Time Series Tools for Business and Economic, 8 contact hours, August 1985
* Statistical Quality Control (Audit), 48 contact hours, September 1983


Note: This resume was created using RMarkdown and was printed on `r format(Sys.Date(), "%A, %B %d, %Y")`. With RMarkdown, you lose some of the fancy formatting available in other programs, but the layout is clean and simple and (most importantly) easy to maintain. You can find the most current version at http://github.com/pmean/resume.
