---
title: "Professional resume of Stephen D. Simon"
fontsize: 12pt
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

```{r read-functions, echo=FALSE}
source("organize-lists.R")
```

`r read_list("contact", number_flag=FALSE, sp="\n")`

`r read_list("personal", number_flag=FALSE, sp="\n")`

`r read_list("education", number_flag=FALSE, sp="\n")`

`r read_list("experience", number_flag=FALSE)`

`r read_list("teaching", number_flag=FALSE, sp="\n\n")`

`r read_list("grants")`

`r read_list("awards")`

`r read_list("committees")`

`r read_list("computer", number_flag=FALSE, sp="\n")`

`r read_list("volunteer efforts")`

`r read_list("hobbies", number_flag=FALSE, sp="\n")`

`r read_list("publications")`

`r read_list("presentations")`

`r read_list("conferences")`

`r read_list("classes")`

Note: This resume was created using RMarkdown and was printed on `r format(Sys.Date(), "%A, %B %d, %Y")`. With RMarkdown, you lose some of the fancy formatting available in other programs, but the layout is clean and simple and (most importantly) easy to maintain. This is a full resume with complete lists of grants, publications, etc. Some of the lists are very long. You can view an abbreviated resume at

https://github.com/pmean/resume/blob/master/results/resume.pdf

You can find the latest version of THIS resume at

https://github.com/pmean/resume/blob/master/results/full-resume.pdf
