---
title: "Professional resume of Stephen D. Simon"
fontsize: 12pt
output: pdf_document
---

```{r read-functions, echo=FALSE}
source("~/resume/src/organize-lists.R")
```

`r read_header("contact")`
`r read_list("contact", number_flag=FALSE)`

`r read_header("personal")`
`r read_list("personal", number_flag=FALSE)`

`r read_header("education")`
`r read_list("education", number_flag=FALSE)`

`r read_header("experience")`
`r read_list("experience", number_flag=FALSE)`

`r read_header("grants")`
`r read_list("grants")`

`r read_header("awards")`
`r read_list("awards")`

`r read_header("professional")`
`r read_list("professional")`

`r read_header("hobbies")`

`r read_header("volunteer")`
`r read_list("volunteer")`

`r read_header("computer")`
`r read_list("computer")`

`r read_header("publications")`
`r read_list("publications")`

`r read_header("presentations")`
`r read_list("presentations")`

`r read_header("conferences")`
`r read_list("conferences")`

`r read_header("training")`
`r read_list("training")`

## Short versions

`r read_short("publications")`

`r read_short("presentations")`

`r read_short("conferences")`

`r read_short("training")`

Note: This resume was created using RMarkdown and was printed on `r format(Sys.Date(), "%A, %B %d, %Y")`. With RMarkdown, you lose some of the fancy formatting available in other programs, but the layout is clean and simple and (most importantly) easy to maintain. You can find the most current version at http://github.com/pmean/resume.
